<?php

return [
    -100=> 'Đơn hàng mới tạo, chưa duyệt',
    -108=> 'Đơn hàng gửi tại bưu cục',
    -109=> 'Đơn hàng đã gửi tại điểm thu gom',
    -110=> 'Đơn hàng đang bàn giao qua bưu cục',
001=>'Đã tạo đơn hàng',
    100=> 'Tiếp nhận đơn hàng từ đối tác "Viettelpost xử lý đơn hàng"',
    101=> 'ViettelPost yêu cầu hủy đơn hàng',
    102=> 'Đơn hàng chờ xử lý',
    103=> 'Giao cho bưu cục "Viettelpost xử lý đơn hàng"',
    104=> 'Giao cho Bưu tá đi nhận',
    105=> 'Buu Tá đã nhận hàng',
    106=> 'Đối tác yêu cầu lấy lại hàng',
    107=> 'Đối tác yêu cầu hủy qua API',
    200=> 'Nhận từ bưu tá - Bưu cục gốc',
    201=> 'Hủy nhập phiếu gửi',
    202=> 'Sửa phiếu gửi',
    300=> 'Close delivery file',
    301=> 'Ðóng túi gói "Vận chuyển đi từ"',
    302=> 'Đóng chuyến thư "Vận chuyển đi từ"',
    303=> 'Đóng tuyến xe "Vận chuyển đi từ"',
    400=> 'Nhận bảng kê đến "Nhận tại"',
    401=> 'Nhận Túi gói "Nhận tại"',
    402=> 'Nhận chuyến thư "Nhận tại"',
    403=> 'Nhận chuyến xe "Nhận tại"',
    500=> 'Giao bưu tá đi phát',
    501=> 'Thành công - Phát thành công',
    502=> 'Chuyển hoàn bưu cục gốc',
    503=> 'Hủy - Theo yêu cầu khách hàng',
    504=> 'Thành công - Chuyển trả người gửi',
    505=> 'Tồn - Thông báo chuyển hoàn bưu cục gốc',
    506=> 'Tồn - Khách hàng nghỉ, không có nhà',
    507=> 'Tồn - Khách hàng đến bưu cục nhận',
    508=> 'Phát tiếp',
    509=> 'Chuyển tiếp bưu cục khác',
    510=> 'Hủy phân công phát',
    515=> 'Bưu cục phát duyệt hoàn',
    550=> 'Đơn Vị Yêu Cầu Phát Tiếp'
];
